version: "3"
services:
  react-frontend:
    build: ./react
    ports:
      - "5173:5173"
    networks:
      assign1-network:
        ipv4_address: 10.5.0.6
  
  express-backend:
    build: ./backend-server
    ports:
      - "3001:3001"
    networks:
      assign1-network:
        ipv4_address: 10.5.0.8

  file-system:
    build: ./fs
    ports:
      - "5000:5000"
    # networks:
    #   assign1-network:
    #     ipv4_address: 10.5.0.7
  mysql:
    image: mysql:latest
    build: ./db
    command: mysqld --default-authentication-plugin=mysql_native_password
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: $ROOTPW
      MYSQL_ROOT_HOST: '%'
    ports: 
      - "33061:3306"
    restart: always
    volumes: 
      - ./mysql:/var/lib/mysql
      - ./db/data.sql:/docker-entrypoint-initdb.d/data.sql



networks:
  assign1-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/24
          gateway: 10.5.0.1


