version: "1.0"
services:
  react-frontend:
    build: .
    ports:
      - "5173:5173"
    networks:
      assign1-network:
        ipv4_address: 10.5.0.6
  express-backend:
    build: ../backend-server
    ports:
      - "3001:3001"
    networks:
      assign1-network:
        ipv4_address: 10.5.0.8

  file-system:
    build: ../fs
    ports:
      - "8080:8080"
    networks:
      assign1-network:
        ipv4_address: 10.5.0.7

networks:
  assign1-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1


